{% set name = "tsid" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stack-of-tasks/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: e6be1045aa5afa0c2a7bf814ea37ef1a62dc84487138805336a2006a542a715d

build:
  number: 2
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - python
    - eigenpy
    - libboost-python-devel
    - eigen
    - pinocchio
    - eiquadprog
    - urdfdom
    - numpy
  run:
    - python
test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
  imports:
    - tsid

about:
  home: http://github.com/stack-of-tasks/tsid
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: TSID is a C++ library for optimization-based inverse-dynamics control based on the rigid multi-body dynamics library Pinocchio.
  dev_url: https://github.com/stack-of-tasks/tsid

extra:
  recipe-maintainers:
    - jorisv
    - EtienneAr
    - jcarpent
